### ISSUE TITLE
Map does not size to window

### ISSUE THREAD

**Issue by paul90** [WefNET/womaps2#1]
Map does not size itself to the window. Affects at least Firefox 59, Firefox 60, and Chrome 66 (not tried other browsers).

![screenshot-2018-5-4 xanadu - wurmonlinemaps com](https://user-images.githubusercontent.com/1552489/39617497-e305ea44-4f77-11e8-81d2-e68c22c8d431.png)

**Comment by WefNET** [comment]
Yeah this is a well known issue for me..  I spent many hours trying to find a happy medium, hence the blue water colored backgrounds.

Do you have any ideas that might help this issue, @paul90 ?

**Comment by paul90** [comment]
I've not used OpenLayers, having only used Leaflet.js for maps, and have not looked at Angular, so...

It looks as if the problem might be in the code writes the initial map canvas `height` and `width`, rather than in the resize window code, as if I manually change the height so it's the height of the window less that of the toolbar and force a map redraw, the map is then sized correctly. 

There is an error that can cause resize to make the canvas height change as the window width is changed - see related error https://github.com/openlayers/openlayers/issues/8040, which hints that the problem has existed for years.

**Comment by WefNET** [comment]
Hey @paul90, thanks for the research into this issue. 

I guess I'll keep this open until a better solution is found.

**Comment by WefNET** [comment]
Fixed following this advice:

[https://stackoverflow.com/a/29294437/2792212](https://stackoverflow.com/a/29294437/2792212)

Embedded styled directly on map element:

 ```html
<div id="map" style="width: 100%; height: 100%; position:fixed">
</div>
```
